SHOP_ID = '5'
SHOP_ORDER_ID = '123456'
SECRET_KEY = 'SecretKey01'
PAYWAY = 'payeer_rub'
PAY_URL = 'https://pay.piastrix.com/ru/pay'
PIASTRIX_URL = 'https://core.piastrix.com/bill/create'
INVOICE_URL = 'https://core.piastrix.com/invoice/create'
SQLALCHEMY_DATABASE_URI = 'sqlite:///dbTest.db'
